Fixed bugs in pre-commit hooks
Bugs:
  - mktemp was called with syntax not supported by OS X
  - the script would call exit from inside a subshell, thus not exiting the
    outer script

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -10,14 +10,27 @@ if [ "$ROOT" == "" ]; then
 	exit 1
 fi
 
-TMP=$(mktemp) || (echo commit aborted >&2; exit 1)
+function die {
+	if [ $# -eq 1 ]; then
+		rm "$1"
+	fi
+	echo "commit aborted" >&1
+	exit 1
+}
+
+# Try to write a temp file first so that we fail
+# cleanly if we can't write to the local filesystem
+# (the errors the go tool outputs are much more
+# messy and verbose).
+TMP=$(mktemp -t kudosXXX) || die
 echo Running '`go fmt ./...`'
-go fmt ./... || (rm $TMP; echo commit aborted >&2; exit 1)
+go fmt ./... || die "$TMP"
 echo Running '`go -a build ./...`'
-go build ./... || (rm $TMP; echo commit aborted >&2; exit 1)
+go build ./... || die "$TMP"
 echo Running '`go build -a -tags dev ./...`'
-go build -tags dev ./... || (rm $TMP; echo commit aborted >&2; exit 1)
+go build -tags dev ./... || die "$TMP"
 echo Running '`go build -a -tags debug ./...`'
-go build -tags debug ./... || (rm $TMP; echo commit aborted >&2; exit 1)
+go build -tags debug ./... || die "$TMP"
 echo Running "\`go build -a -tags 'dev debug'./...\`"
-go build -tags 'dev debug' ./... || (rm $TMP; echo commit aborted >&2; exit 1)
+go build -tags 'dev debug' ./... || die "$TMP"
+rm "$TMP"
